name: Build & Deploy Floatly-Server (.NET 10 - Ubuntu VPS)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    env:
      PROJECT_PATH: Floatly-Server.csproj
      PUBLISH_TMP: /tmp/floatly-publish
      PUBLISH_DIR: /var/www/floatly

    steps:
      - name: 💕 Checkout repository
        uses: actions/checkout@v4

      - name: 💿 Verify .NET SDK
        run: dotnet --info

      - name: 🧰 Install LibMan CLI
        run: dotnet tool install -g Microsoft.Web.LibraryManager.Cli || true

      - name: 🔧 Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: 📦 Restore dependencies
        run: |
          dotnet restore
          libman restore

      - name: 🧱 Build
        run: dotnet build -c Release --no-restore

      - name: 🚀 Publish
        run: |
          rm -rf $PUBLISH_TMP
          dotnet publish ${{ env.PROJECT_PATH }} -c Release -o $PUBLISH_TMP

      - name: 🌸 Deploy to VPS & Restart
        run: |
          sudo systemctl stop floatly || true
          sudo rm -rf ${{ env.PUBLISH_DIR }}/*
          sudo cp -r $PUBLISH_TMP/* ${{ env.PUBLISH_DIR }}
          sudo systemctl start floatly
